apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-argocd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: hello-argocd.10.20.20.50.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-argocd
            port:
              number: 80
